language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: HIbojDEEMsZpaPvsHWvpj+Lu07pAAu4iTQp7rhUW/8ZxxSvlgMWpHmrgoWg0WqI1NJPleSQqk54MQY+wOWnToO/b7S74m2B/O5CyN1PLaFUX1V/wOrhBcuz70u0KQ3UW6pCGOqvy9jeuh4/KOWQQ4gdAnpewaNWsm3FV0N44Xes=
  - secure: AkYzOoFwUxSbdTbdSal5Euq3LYhJ1hmJrLiIsXCjWYadD9dLhZe9cYtwEKD1G/BMet0h7c8YYFlsqNgiC5f21w9Zwc8YyHvEvNZNPcoNmWFVM/4pohLAagZlKnUJzdsm3opEURiB1tad6zlyt+bYsRm4QoVdMocm4LWNrYYCebY=
  - secure: O/WzfMnNhpDV2w/7gc2a9u1AFxBwkuj4kKJh14xpri9UwT9TWJnC5KEoiX8jMIPWr9cyqyVn2tq1So2AnLlaNnSPYm7ZE14kj+YQBmyzQU/94kbPXyt7XLYLwEvSbXil7pu8YRxzFTbivOkMsL74b0hNZONtG9LZ0DAWciYRk+g=
notifications:
  slack:
    secure: Pbx6yo7HCgoB3w2IU9WXznn20sZVucwO5De9syYx07j8G1VqfWIXIc0TXEGMe7C9xOJBiMww0b7VAxIU5glN4rAo0W9KeuUxCynTqrXjugtxULvaGrpJi7SXSLYIBaJYCSkm+k0VVh7nMnI9zYQTUwwaH/IXZSJpL1aFCwA+EH8=
